// eb2646b61337a434f6bbe67f439a4a7bf25dd216
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "g4.7.0pre-iOS"
#define GIT_HASH "eb2646b61337a434f6bbe67f439a4a7bf25dd216"
#define GIT_TIME "2021-07-13 06:32:38 -0400"
